[package]
name = "proxyroute"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.90"
as-any = "0.3.1"
log = "0.4.22"
socks5-impl = "0.5.15"
tokio = "1.41.0"
url = "2.5.2"

[[example]]
name = "localroute"
